CC = gcc
CFLAGS = -g
FILES = json_parser.c main.c json_parser_utilities.c json_parser_file_utilities.c
TARGET = arsn


build: $(FILES)
	$(CC) $(CFLAGS) -o $(TARGET) $(FILES)


#test:
	# build then run tests


clean:
	rm -f *.o *.dSYM